### ISSUE TITLE
Implement compress.js functions.

### ISSUE THREAD

**Issue by alikhil** [alikhil/sttp#1]
Implement compress.js functions.

- compress(str)

- decompress(str)

All tests in compress-tests.js should pass.

**Comment by Nothing-personal** [comment]
Working on it

**Comment by Nothing-personal** [comment]
Functions are now working with "lz-string" library. Looking forward to implement some of algorithms for compression. Simpliest that comes in mind - one that depends on symbol probability. It can be based using Map, where symbols are keys and values are counters.
